name: Releases
on:
  push:
    branches:
      - main
jobs:
  changelog:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Check if bot created the branch
        if: github.actor == 'github-actions[bot]' && github.ref == 'refs/heads/main'
        run: exit 0
        
      - name: create branch
        uses: peterjgrainger/action-create-branch@v2.3.0
        id: create-branch
        with:
          branch: "release-from-${{ github.sha }}"
          sha: "${{ github.sha }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v3

      # fetch branches and switch to the temporary branch
      - name: switch to new branch
        run: git fetch --all && git checkout --track origin/release-from-${{ github.sha }}

      # create release info and push it upstream
      - name: conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version-file: "./package.json,./package-lock.json"
          git-branch: "release-from-${{ github.sha }}"
          skip-on-empty: false
          skip-git-pull: true

      # create PR using GitHub CLI
      - name: create PR with release info
        id: create-pr
        run: gh pr create --base main --head release-from-${{ github.sha }} --title 'Merge new release into main' --body 'Created by Github action'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
